name: 'Yandex Lockbox Sync'
description:
  'Action for getting secrets from Yandex Lockbox by prefix / Action для
  загрузки секретов из Lockbox по префиксу'
author: 'MIMBOL22'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  iam_token:
    description: 'Your IAM Token / Ваш IAM токен'
    required: true
  folder_id:
    description: 'ID of folder in your Cloud / ID вашей папки в облаке'
    required: true
  secret_prefix:
    description: 'Prefix of secrets / Префикс ваших секретов'
    required: true
  is_clean_prefix:
    description:
      'Is need to delete prefix in variables (true or false) / Нужно ли удалять
      префикс в итоговой переменной (true или false)'
    required: false
    default: false

runs:
  using: node20
  main: dist/index.js
